"""update_field_lengths_from_env

Revision ID: 9d3952421f6b
Revises: ec7e39871e84
Create Date: 2025-11-28 01:19:55.749572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3952421f6b'
down_revision: Union[str, Sequence[str], None] = 'ec7e39871e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
