from typing import Protocol, List, Optional

from ..core.entities import Project, Task


class StorageProtocol(Protocol):
    """Protocol defining storage operations."""
    
    def create_project(self, project: Project) -> Project: ...
    def get_project(self, project_id: int) -> Optional[Project]: ...
    def get_all_projects(self) -> List[Project]: ...
    def update_project(self, project: Project) -> Project: ...
    def delete_project(self, project_id: int) -> bool: ...
    def project_name_exists(self, name: str, exclude_project_id: Optional[int] = None) -> bool: ...
    def create_task(self, task: Task) -> Task: ...
    def get_task(self, task_id: int) -> Optional[Task]: ...
    def get_tasks_by_project(self, project_id: int) -> List[Task]: ...
    def update_task(self, task: Task) -> Task: ...
    def delete_task(self, task_id: int) -> bool: ...
    def get_project_count(self) -> int: ...
    def get_task_count(self, project_id: Optional[int] = None) -> int: ...
